package com.course.model;

/*
把接口名称定义成枚举，这样能保证接口名称是正确的
 */
public enum InterfaceName {
    DOLOGIN,TESTDOLOGIN,GETMERCHANTLIST,GETCARWASHDETAIL,GETCARWASHDETAILURITWOURI,SENDVERIFICATIONCODEURI,SEARCHMERCHANTLISTURI,LOADURI,CREATEURI
}
