package com.course.controller;


import org.mybatis.dao.annotation.Table;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cfw_shop
 *
 * @mbg.generated do_not_delete_during_merge Thu Nov 15 11:35:38 CST 2018
 */
@Table("cfw_shop")
public class Shop implements Serializable {
    private Integer id;

    private String shopName;

    private String shopLogo;

    private String shopAddr;

    private String shopPhone;

    private Integer provinceId;

    private Integer cityId;

    private Integer countyId;

    private String shopIntro;

    private Date createdTime;

    private Date modifiedTime;

    private Integer status;

    private Integer isRoll;

    private Integer showStatus;

    private Integer kxxsId;

    private Integer shopGroup;

    private String shopNo;

    private String remark;

    private String bannerImgs;

    private String serviceIntro;

    private Date agreementStartTime;

    private Date agreementEndTime;

    private String tags;

    private String types;

    private String creatorId;

    private String creatorName;

    private String editorId;

    private String editorName;

    private BigDecimal bdLongitude;

    private BigDecimal bdLatitude;

    private BigDecimal txLongitude;

    private BigDecimal txLatitude;

    private Date serviceStime;

    private Date serviceEtime;

    private Integer serviceIntroMode;

    private String activityTags;

    private Integer baseRecommendCount;

    private Integer recommentCount;

    private Integer recommentScore;

    private Integer platformScore;

    private static final long serialVersionUID = 1L;

    /**
     * 主键
     *
     * @return cfw_shop.id 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 主键
     *
     * @param id 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 门店名称
     *
     * @return cfw_shop.shop_name 门店名称
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * 门店名称
     *
     * @param shopName 门店名称
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * 门店logo
     *
     * @return cfw_shop.shop_logo 门店logo
     */
    public String getShopLogo() {
        return shopLogo;
    }

    /**
     * 门店logo
     *
     * @param shopLogo 门店logo
     */
    public void setShopLogo(String shopLogo) {
        this.shopLogo = shopLogo == null ? null : shopLogo.trim();
    }

    /**
     * 门店地址
     *
     * @return cfw_shop.shop_addr 门店地址
     */
    public String getShopAddr() {
        return shopAddr;
    }

    /**
     * 门店地址
     *
     * @param shopAddr 门店地址
     */
    public void setShopAddr(String shopAddr) {
        this.shopAddr = shopAddr == null ? null : shopAddr.trim();
    }

    /**
     * 门店电话
     *
     * @return cfw_shop.shop_phone 门店电话
     */
    public String getShopPhone() {
        return shopPhone;
    }

    /**
     * 门店电话
     *
     * @param shopPhone 门店电话
     */
    public void setShopPhone(String shopPhone) {
        this.shopPhone = shopPhone == null ? null : shopPhone.trim();
    }

    /**
     * 省份代码
     *
     * @return cfw_shop.province_id 省份代码
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * 省份代码
     *
     * @param provinceId 省份代码
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * 城市代码
     *
     * @return cfw_shop.city_id 城市代码
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * 城市代码
     *
     * @param cityId 城市代码
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * 区县代码
     *
     * @return cfw_shop.county_id 区县代码
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * 区县代码
     *
     * @param countyId 区县代码
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * 门店介绍
     *
     * @return cfw_shop.shop_intro 门店介绍
     */
    public String getShopIntro() {
        return shopIntro;
    }

    /**
     * 门店介绍
     *
     * @param shopIntro 门店介绍
     */
    public void setShopIntro(String shopIntro) {
        this.shopIntro = shopIntro == null ? null : shopIntro.trim();
    }

    /**
     * 创建时间
     *
     * @return cfw_shop.created_time 创建时间
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * 创建时间
     *
     * @param createdTime 创建时间
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 修改时间
     *
     * @return cfw_shop.modified_time 修改时间
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * 修改时间
     *
     * @param modifiedTime 修改时间
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * 删除标志0:有效，1:删除，2:待审核
     *
     * @return cfw_shop.status 删除标志0:有效，1:删除，2:待审核
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * 删除标志0:有效，1:删除，2:待审核
     *
     * @param status 删除标志0:有效，1:删除，2:待审核
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 网点是否可以派单设置：0未知;1:白名单可派单;2:不可派单;3-暂停派单
     *
     * @return cfw_shop.is_roll 网点是否可以派单设置：0未知;1:白名单可派单;2:不可派单;3-暂停派单
     */
    public Integer getIsRoll() {
        return isRoll;
    }

    /**
     * 网点是否可以派单设置：0未知;1:白名单可派单;2:不可派单;3-暂停派单
     *
     * @param isRoll 网点是否可以派单设置：0未知;1:白名单可派单;2:不可派单;3-暂停派单
     */
    public void setIsRoll(Integer isRoll) {
        this.isRoll = isRoll;
    }

    /**
     * 展示状态0展示1不展示2待处理3初始
     *
     * @return cfw_shop.show_status 展示状态0展示1不展示2待处理3初始
     */
    public Integer getShowStatus() {
        return showStatus;
    }

    /**
     * 展示状态0展示1不展示2待处理3初始
     *
     * @param showStatus 展示状态0展示1不展示2待处理3初始
     */
    public void setShowStatus(Integer showStatus) {
        this.showStatus = showStatus;
    }

    /**
     * 外部系统 id
     *
     * @return cfw_shop.kxxs_id 外部系统 id
     */
    public Integer getKxxsId() {
        return kxxsId;
    }

    /**
     * 外部系统 id
     *
     * @param kxxsId 外部系统 id
     */
    public void setKxxsId(Integer kxxsId) {
        this.kxxsId = kxxsId;
    }

    /**
     * 门店组 0-易鑫；1-快修先生；2-康得新；
     *
     * @return cfw_shop.shop_group 门店组 0-易鑫；1-快修先生；2-康得新；
     */
    public Integer getShopGroup() {
        return shopGroup;
    }

    /**
     * 门店组 0-易鑫；1-快修先生；2-康得新；
     *
     * @param shopGroup 门店组 0-易鑫；1-快修先生；2-康得新；
     */
    public void setShopGroup(Integer shopGroup) {
        this.shopGroup = shopGroup;
    }

    /**
     * 门店编号
     *
     * @return cfw_shop.shop_no 门店编号
     */
    public String getShopNo() {
        return shopNo;
    }

    /**
     * 门店编号
     *
     * @param shopNo 门店编号
     */
    public void setShopNo(String shopNo) {
        this.shopNo = shopNo == null ? null : shopNo.trim();
    }

    /**
     * 备注
     *
     * @return cfw_shop.remark 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 备注
     *
     * @param remark 备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * banner 图
     *
     * @return cfw_shop.banner_imgs banner 图
     */
    public String getBannerImgs() {
        return bannerImgs;
    }

    /**
     * banner 图
     *
     * @param bannerImgs banner 图
     */
    public void setBannerImgs(String bannerImgs) {
        this.bannerImgs = bannerImgs == null ? null : bannerImgs.trim();
    }

    /**
     * 服务须知
     *
     * @return cfw_shop.service_intro 服务须知
     */
    public String getServiceIntro() {
        return serviceIntro;
    }

    /**
     * 服务须知
     *
     * @param serviceIntro 服务须知
     */
    public void setServiceIntro(String serviceIntro) {
        this.serviceIntro = serviceIntro == null ? null : serviceIntro.trim();
    }

    /**
     * 合同开始时间
     *
     * @return cfw_shop.agreement_start_time 合同开始时间
     */
    public Date getAgreementStartTime() {
        return agreementStartTime;
    }

    /**
     * 合同开始时间
     *
     * @param agreementStartTime 合同开始时间
     */
    public void setAgreementStartTime(Date agreementStartTime) {
        this.agreementStartTime = agreementStartTime;
    }

    /**
     * 合同结束时间
     *
     * @return cfw_shop.agreement_end_time 合同结束时间
     */
    public Date getAgreementEndTime() {
        return agreementEndTime;
    }

    /**
     * 合同结束时间
     *
     * @param agreementEndTime 合同结束时间
     */
    public void setAgreementEndTime(Date agreementEndTime) {
        this.agreementEndTime = agreementEndTime;
    }

    /**
     * 商户标签
     *
     * @return cfw_shop.tags 商户标签
     */
    public String getTags() {
        return tags;
    }

    /**
     * 商户标签
     *
     * @param tags 商户标签
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * 商户类型
     *
     * @return cfw_shop.types 商户类型
     */
    public String getTypes() {
        return types;
    }

    /**
     * 商户类型
     *
     * @param types 商户类型
     */
    public void setTypes(String types) {
        this.types = types == null ? null : types.trim();
    }

    /**
     * 创建人ID
     *
     * @return cfw_shop.creator_id 创建人ID
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * 创建人ID
     *
     * @param creatorId 创建人ID
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * 创建人姓名
     *
     * @return cfw_shop.creator_name 创建人姓名
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * 创建人姓名
     *
     * @param creatorName 创建人姓名
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * 修改人ID
     *
     * @return cfw_shop.editor_id 修改人ID
     */
    public String getEditorId() {
        return editorId;
    }

    /**
     * 修改人ID
     *
     * @param editorId 修改人ID
     */
    public void setEditorId(String editorId) {
        this.editorId = editorId == null ? null : editorId.trim();
    }

    /**
     * 修改人姓名
     *
     * @return cfw_shop.editor_name 修改人姓名
     */
    public String getEditorName() {
        return editorName;
    }

    /**
     * 修改人姓名
     *
     * @param editorName 修改人姓名
     */
    public void setEditorName(String editorName) {
        this.editorName = editorName == null ? null : editorName.trim();
    }

    /**
     * 百度坐标-经度
     *
     * @return cfw_shop.bd_longitude 百度坐标-经度
     */
    public BigDecimal getBdLongitude() {
        return bdLongitude;
    }

    /**
     * 百度坐标-经度
     *
     * @param bdLongitude 百度坐标-经度
     */
    public void setBdLongitude(BigDecimal bdLongitude) {
        this.bdLongitude = bdLongitude;
    }

    /**
     * 百度坐标-纬度
     *
     * @return cfw_shop.bd_latitude 百度坐标-纬度
     */
    public BigDecimal getBdLatitude() {
        return bdLatitude;
    }

    /**
     * 百度坐标-纬度
     *
     * @param bdLatitude 百度坐标-纬度
     */
    public void setBdLatitude(BigDecimal bdLatitude) {
        this.bdLatitude = bdLatitude;
    }

    /**
     * 腾讯高德坐标-经度
     *
     * @return cfw_shop.tx_longitude 腾讯高德坐标-经度
     */
    public BigDecimal getTxLongitude() {
        return txLongitude;
    }

    /**
     * 腾讯高德坐标-经度
     *
     * @param txLongitude 腾讯高德坐标-经度
     */
    public void setTxLongitude(BigDecimal txLongitude) {
        this.txLongitude = txLongitude;
    }

    /**
     * 腾讯高德-纬度
     *
     * @return cfw_shop.tx_latitude 腾讯高德-纬度
     */
    public BigDecimal getTxLatitude() {
        return txLatitude;
    }

    /**
     * 腾讯高德-纬度
     *
     * @param txLatitude 腾讯高德-纬度
     */
    public void setTxLatitude(BigDecimal txLatitude) {
        this.txLatitude = txLatitude;
    }

    /**
     * 服务开始时间
     *
     * @return cfw_shop.service_stime 服务开始时间
     */
    public Date getServiceStime() {
        return serviceStime;
    }

    /**
     * 服务开始时间
     *
     * @param serviceStime 服务开始时间
     */
    public void setServiceStime(Date serviceStime) {
        this.serviceStime = serviceStime;
    }

    /**
     * 服务结束时间
     *
     * @return cfw_shop.service_etime 服务结束时间
     */
    public Date getServiceEtime() {
        return serviceEtime;
    }

    /**
     * 服务结束时间
     *
     * @param serviceEtime 服务结束时间
     */
    public void setServiceEtime(Date serviceEtime) {
        this.serviceEtime = serviceEtime;
    }

    /**
     * 服务说明模式 0-图片；1-文本；
     *
     * @return cfw_shop.service_intro_mode 服务说明模式 0-图片；1-文本；
     */
    public Integer getServiceIntroMode() {
        return serviceIntroMode;
    }

    /**
     * 服务说明模式 0-图片；1-文本；
     *
     * @param serviceIntroMode 服务说明模式 0-图片；1-文本；
     */
    public void setServiceIntroMode(Integer serviceIntroMode) {
        this.serviceIntroMode = serviceIntroMode;
    }

    /**
     * 活动标签
     *
     * @return cfw_shop.activity_tags 活动标签
     */
    public String getActivityTags() {
        return activityTags;
    }

    /**
     * 活动标签
     *
     * @param activityTags 活动标签
     */
    public void setActivityTags(String activityTags) {
        this.activityTags = activityTags == null ? null : activityTags.trim();
    }

    /**
     * 推荐次数初始值
     *
     * @return cfw_shop.base_recommend_count 推荐次数初始值
     */
    public Integer getBaseRecommendCount() {
        return baseRecommendCount;
    }

    /**
     * 推荐次数初始值
     *
     * @param baseRecommendCount 推荐次数初始值
     */
    public void setBaseRecommendCount(Integer baseRecommendCount) {
        this.baseRecommendCount = baseRecommendCount;
    }

    /**
     * 推荐次数
     *
     * @return cfw_shop.recomment_count 推荐次数
     */
    public Integer getRecommentCount() {
        return recommentCount;
    }

    /**
     * 推荐次数
     *
     * @param recommentCount 推荐次数
     */
    public void setRecommentCount(Integer recommentCount) {
        this.recommentCount = recommentCount;
    }

    /**
     * 推荐次数评分
     *
     * @return cfw_shop.recomment_score 推荐次数评分
     */
    public Integer getRecommentScore() {
        return recommentScore;
    }

    /**
     * 推荐次数评分
     *
     * @param recommentScore 推荐次数评分
     */
    public void setRecommentScore(Integer recommentScore) {
        this.recommentScore = recommentScore;
    }

    /**
     * 平台评分
     *
     * @return cfw_shop.platform_score 平台评分
     */
    public Integer getPlatformScore() {
        return platformScore;
    }

    /**
     * 平台评分
     *
     * @param platformScore 平台评分
     */
    public void setPlatformScore(Integer platformScore) {
        this.platformScore = platformScore;
    }

}
