package com.course.controller;

import org.mybatis.dao.annotation.Table;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table gc_sku
 *
 * @mbg.generated do_not_delete_during_merge Tue Aug 14 14:45:57 CST 2018
 */
@Table("gc_sku")
public class Sku implements Serializable {
    private Long id;

    private String skuCode;

    private Long goodsId;

    private BigDecimal salePrice;

    private BigDecimal originalPrice;

    private BigDecimal costPrice;

    private Integer stock;

    private Integer lockStock;

    private String attributes;

    private String attributeValue;

    private String images;

    private Date createdTime;

    private Date modifiedTime;

    private Short status;

    private static final long serialVersionUID = 1L;

    /**
     *
     *
     * @return gc_sku.id
     */
    public Long getId() {
        return id;
    }

    /**
     *
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * sku编号
     *
     * @return gc_sku.sku_code sku编号
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * sku编号
     *
     * @param skuCode sku编号
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    /**
     * 商品ID
     *
     * @return gc_sku.goods_id 商品ID
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * 商品ID
     *
     * @param goodsId 商品ID
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * 售价
     *
     * @return gc_sku.sale_price 售价
     */
    public BigDecimal getSalePrice() {
        return salePrice;
    }

    /**
     * 售价
     *
     * @param salePrice 售价
     */
    public void setSalePrice(BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * 原价
     *
     * @return gc_sku.original_price 原价
     */
    public BigDecimal getOriginalPrice() {
        return originalPrice;
    }

    /**
     * 原价
     *
     * @param originalPrice 原价
     */
    public void setOriginalPrice(BigDecimal originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * 成本价
     *
     * @return gc_sku.cost_price 成本价
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * 成本价
     *
     * @param costPrice 成本价
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * 库存
     *
     * @return gc_sku.stock 库存
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * 库存
     *
     * @param stock 库存
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * 锁定库存
     *
     * @return gc_sku.lock_stock 锁定库存
     */
    public Integer getLockStock() {
        return lockStock;
    }

    /**
     * 锁定库存
     *
     * @param lockStock 锁定库存
     */
    public void setLockStock(Integer lockStock) {
        this.lockStock = lockStock;
    }

    /**
     * spu属性 json
     *
     * @return gc_sku.attributes spu属性 json
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * spu属性 json
     *
     * @param attributes spu属性 json
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }

    /**
     * sku 值
     *
     * @return gc_sku.attribute_value sku 值
     */
    public String getAttributeValue() {
        return attributeValue;
    }

    /**
     * sku 值
     *
     * @param attributeValue sku 值
     */
    public void setAttributeValue(String attributeValue) {
        this.attributeValue = attributeValue == null ? null : attributeValue.trim();
    }

    /**
     * 图片
     *
     * @return gc_sku.images 图片
     */
    public String getImages() {
        return images;
    }

    /**
     * 图片
     *
     * @param images 图片
     */
    public void setImages(String images) {
        this.images = images == null ? null : images.trim();
    }

    /**
     * 创建时间
     *
     * @return gc_sku.created_time 创建时间
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * 创建时间
     *
     * @param createdTime 创建时间
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * 修改时间
     *
     * @return gc_sku.modified_time 修改时间
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * 修改时间
     *
     * @param modifiedTime 修改时间
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * 0-正常；1-软删除
     *
     * @return gc_sku.status 0-正常；1-软删除
     */
    public Short getStatus() {
        return status;
    }

    /**
     * 0-正常；1-软删除
     *
     * @param status 0-正常；1-软删除
     */
    public void setStatus(Short status) {
        this.status = status;
    }


}
